services:
  - type: web
    name: phi2-llm-server
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars: 
      - key: PYTHONPATH
      value: .
